env:
  global:
    - CC_TEST_REPORTER_ID=31ad6fc12100f681ef0f1f0c9dcf4aa390736d8bc613983c3fee5f33206ef299

language: python
python: 3.8

instal:
  - pip install poetry
  - make
  - poetry install
  - pip install flake8

script:
  - make lint
  - make tests

# single test suite, non-parallel build.
