[tool.poetry]
name = "franky_gendiff"
version = "0.3.0"
description = ""
authors = ["Your Name <you@example.com>"]

packages = [
  { include = "gendiff" },
]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^5.3.5"
pytest-cov = "^2.8.1"
flake8 = "^3.7.9"
PyYAML = "^5.3"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"

[tool.poetry.scripts]
gendiff-json= "gendiff.scripts.gendiff_json:main"
gendiff-yaml= "gendiff.scripts.gendiff_yaml:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"