[tool.poetry]
name = "franky_gendiff"
version = "0.1.8"
description = ""
authors = ["Your Name <you@example.com>"]

packages = [
  { include = "gendiff" },
]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^5.3.5"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"

[tool.poetry.scripts]
gendiff = "gendiff.scripts.gendiff:main"
test = "gendiff.tests.gendiff_test:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"